name: Run clang-format Linter

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Pull latest changes
      run: |
        git config --global user.name "Clang Robot"
        git config --global user.email "robot@example.com"
        git pull --rebase origin main

    - uses: DoozyX/clang-format-lint-action@v0.20
      with:
        source: '.'
        exclude: './驱动库/FatFs-R0.16'
        extensions: 'h,hpp,cpp,c'
        clangFormatVersion: 20
        style: Microsoft
        inplace: true

    - uses: EndBug/add-and-commit@v9
      with:
        author_name: Clang Robot
        author_email: robot@example.com
        message: 'Committing clang-format changes'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
